# Generated by Django 6.0.3 on 2026-04-02 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_alter_asset_asset_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('DIVIDENDS', 'Dividends'), ('EXTRAS', 'Extras / Other Income'), ('HOUSEHOLD', 'Household & Supplies'), ('SERVICES', 'Utilities & Services'), ('SUBSCRIPTIONS', 'Subscriptions'), ('ENTERTAINMENT', 'Entertainment'), ('TECHNOLOGY', 'Technology & Tools'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(blank=True, help_text='Select the bank account or cash reserve for this transaction.', limit_choices_to={'asset_type__in': ['Bank Account', 'Cash Reserve']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
