# Generated by Django 6.0.3 on 2026-04-02 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., DNB Debit Account', max_length=100)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank Account'), ('CASH', 'Cash Wallet'), ('CREDIT', 'Credit Card')], max_length=20)),
                ('currency', models.CharField(default='USD', help_text='e.g., USD, NOK, EUR', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Select the account or wallet for this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.account'),
        ),
    ]
