# Generated by Django 6.0.5 on 2026-05-31 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_balance_account_initial_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='budget.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_class',
            field=models.CharField(choices=[('CURRENT_ASSET', 'Current Asset'), ('CURRENT_LIABILITY', 'Current Liability')], default='CURRENT_ASSET', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Current Assets', [('CASH', 'Physical Cash'), ('CHECKING', 'Checking Account'), ('SAVINGS', 'Savings Account'), ('E-WALLET', 'Digital Wallet (PayPal/Revolut)')]), ('Current Liabilities', [('CREDIT_CARD', 'Credit Card'), ('OVERDRAFT', 'Bank Overdraft'), ('LINE_OF_CREDIT', 'Line of Credit')])], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='NOK', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Income', [('SALARY', 'Salary'), ('DIVIDENDS', 'Dividends'), ('EXTRAS', 'Extras / Other Income')]), ('Expenses', [('HOUSEHOLD', 'Household & Supplies'), ('SERVICES', 'Utilities & Services'), ('SUBSCRIPTIONS', 'Subscriptions'), ('ENTERTAINMENT', 'Entertainment'), ('TECHNOLOGY', 'Technology & Tools'), ('OTHER', 'Other')])], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
    ]
