# Generated by Django 6.0.5 on 2026-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_account_credit_limit_transaction_destination_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payment_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Fee the bank charges each time you pay this card/liability.', max_digits=12),
        ),
    ]
