# Generated by Django 6.0.3 on 2026-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_calculator_type_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='calculator_type',
            field=models.CharField(choices=[('loan', 'Loan Calculator'), ('mortgage', 'Mortgage Calculator'), ('rent_vs_own', 'Rent vs Own')], max_length=50),
        ),
    ]
