# Generated by Django 6.0.3 on 2026-04-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_asset_type'),
        ('projects', '0003_alter_project_calculator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linked_asset',
            field=models.ForeignKey(blank=True, help_text='Optionally link a real asset you own to pre-fill calculator fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='assets.asset'),
        ),
    ]
