# Generated by Django 6.0.3 on 2026-03-30 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50)),
                ('asset_type', models.CharField(choices=[('Property & Land', 'Property & Land'), ('Equipment & Machinery', 'Equipment & Machinery'), ('Furniture', 'Furniture'), ('Long-Term Investments', 'Long-Term Investments')], max_length=50)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('value_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_year', models.PositiveIntegerField()),
                ('active_Status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
