# Generated by Django 6.0.3 on 2026-04-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('Bank Account', 'Bank Account'), ('Cash Reserve', 'Cash Reserve / Equivalent'), ('Property & Land', 'Property & Land'), ('Equipment & Machinery', 'Equipment & Machinery'), ('Furniture', 'Furniture'), ('Long-Term Investments', 'Long-Term Investments')], max_length=50),
        ),
    ]
