# Generated by Django 6.0.3 on 2026-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('Property & Land', 'Property & Land'), ('Equipment & Machinery', 'Equipment & Machinery'), ('Furniture', 'Furniture'), ('Long-Term Investments', 'Long-Term Investments')], max_length=50),
        ),
    ]
