# Generated by Django 6.0.5 on 2026-06-01 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_asset_type'),
        ('liabilities', '0002_liability_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_subtype',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='debt_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% of purchase price financed, e.g. 80 for 80%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_debt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='linked_liability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financed_assets', to='liabilities.liability'),
        ),
        migrations.AddField(
            model_name='asset',
            name='make_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacture_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='mileage_km',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='asset',
            name='property_status',
            field=models.CharField(blank=True, choices=[('Commercial', 'Commercial'), ('Residential', 'Residential / Housing'), ('Industrial', 'Industrial'), ('Land', 'Land / Plot'), ('Mixed-Use', 'Mixed-Use'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('Property & Land', 'Property & Land'), ('Vehicles', 'Vehicles'), ('Equipment & Machinery', 'Equipment & Machinery'), ('Furniture & Fixtures', 'Furniture & Fixtures'), ('Long-Term Investments', 'Long-Term Investments')], max_length=50),
        ),
    ]
