# Generated by Django 6.0.5 on 2026-06-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_address_asset_area_sqm_asset_asset_subtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='address',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='area_sqm',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_subtype',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='city',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='debt_percentage',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='down_payment',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='has_debt',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='linked_liability',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='make_model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='manufacture_year',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='mileage_km',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='property_status',
        ),
    ]
