# Generated by Django 6.0.5 on 2026-06-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_asset_address_remove_asset_area_sqm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='active_Status',
            new_name='active_status',
        ),
    ]
