# Generated by Django 6.0.3 on 2026-03-30 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_asset_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_name', models.CharField(max_length=100)),
                ('liability_type', models.CharField(choices=[('Mortgage', 'Mortgage'), ('Car Loan', 'Car Loan'), ('Student Loan', 'Student Loan'), ('Credit Card', 'Credit Card Debt'), ('Other', 'Other')], max_length=50)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='e.g. 5.5 for 5.5%', max_digits=5)),
                ('linked_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Liabilities',
            },
        ),
    ]
