# Generated by Django 6.0.5 on 2026-06-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0002_liability_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='lender',
            field=models.CharField(blank=True, default='', help_text='Bank or institution name', max_length=100),
        ),
        migrations.AddField(
            model_name='liability',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='liability',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='term_months',
            field=models.PositiveIntegerField(blank=True, help_text='Total loan term in months, e.g. 360 for 30 years', null=True),
        ),
        migrations.AlterField(
            model_name='liability',
            name='liability_type',
            field=models.CharField(choices=[('Mortgage', 'Mortgage'), ('Car Loan', 'Car Loan'), ('Student Loan', 'Student Loan'), ('Personal Loan', 'Personal Loan'), ('Business Loan', 'Business Loan'), ('Other', 'Other')], max_length=50),
        ),
    ]
