# Generated by Django 6.0.5 on 2026-06-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0003_liability_lender_liability_monthly_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liability',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
