# Generated by Django 6.0.3 on 2026-03-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term_type",
                    models.CharField(
                        choices=[
                            ("loan", "Loan"),
                            ("mortgage", "Mortgage"),
                            ("budget", "Budget"),
                            ("housing", "Housing"),
                            ("general", "General Finance"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("term", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("definition", models.TextField()),
            ],
            options={
                "ordering": ["term"],
            },
        ),
    ]
