# Generated by Django 6.0.3 on 2026-03-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_seed_glossary_terms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glossaryterm",
            options={
                "ordering": ["term"],
                "permissions": [("manage_glossary", "Can manage glossary content")],
            },
        ),
    ]
