# Generated by Django 6.0.3 on 2026-04-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
        ('projects', '0003_alter_project_calculator_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='project',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='budget',
        ),
        migrations.CreateModel(
            name='LoanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('years', models.IntegerField(default=0)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_data', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MortgageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('years', models.IntegerField(default=0)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_data', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='RentVsOwnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_increase', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_vs_own_data', to='projects.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
