# Generated by Django 6.0.5 on 2026-06-03 14:10

import calculators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_remove_budget_project_remove_budget_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandata',
            name='start_year',
            field=models.IntegerField(default=calculators.models.current_year),
        ),
        migrations.AddField(
            model_name='mortgagedata',
            name='start_year',
            field=models.IntegerField(default=calculators.models.current_year),
        ),
    ]
