# Generated by Django 6.0.5 on 2026-06-03 21:08

import calculators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0003_loandata_start_year_mortgagedata_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentvsowndata',
            name='start_year',
            field=models.IntegerField(default=calculators.models.current_year),
        ),
        migrations.AddField(
            model_name='rentvsowndata',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]
